import 'package:healthso/views/Resources/Doctors/doctor_model.dart';

class DoctorData {
  static final List<Doctor> doctors = [
    Doctor(
      docId: 1,
      name: "John Wilson",
      domain: "Cardiology",
      distance: "1.0",
      ratings: "4.0",
      imagePath: 'assets/popularDoc/John.png',
      bio:
          'Dr. Carly Angel is the top most immunologists specialist \nin Crist Hospital in London, UK. She achieved several awards for her wonderful contribution.',
      extendedBio: '',
      hospitalName: 'Mars Hospital',
      experienceYearsCount: '11',
      patientCount: '658',
      reviewsCount: '300',
    ),
    
    Doctor(
      docId: 2,
      name: "Alexa Johnson",
      domain: "Heart Surgeon",
      distance: "1.8",
      ratings: "4.2",
      imagePath: 'assets/popularDoc/Alexa.png',
      bio: 'ADD',
      extendedBio: '',
      hospitalName: 'Mars Hospital',
      experienceYearsCount: '11',
      patientCount: '658',
      reviewsCount: '300',
    ),
      Doctor(
      docId: 3,
      name: "Wadw Warren",
      domain: "Microbiologist",
      distance: "800",
      ratings: "4.1",
      imagePath: 'assets/popularDoc/Wadw.png',
      bio: 'ADD',
      extendedBio: '',
      hospitalName: 'Mars Hospital',
      experienceYearsCount: '11',
      patientCount: '658',
      reviewsCount: '300',
    ),
    Doctor(
      docId: 4,
      name: "Leslie Alexander",
      domain: "Cardiology",
      distance: "1.9",
      ratings: "4.0",
      imagePath: 'assets/popularDoc/Leslie.png',
      bio: 'ADD',
      extendedBio: '',
      hospitalName: 'Mars Hospital',
      experienceYearsCount: '11',
      patientCount: '658',
      reviewsCount: '300',
    ),
    Doctor(
      docId: 5,
      name: "Jacob Jones",
      domain: "Physiotherapist",
      distance: "2.0",
      ratings: "4.2",
      imagePath: 'assets/popularDoc/Jacob.png',
      bio: 'ADD',
      extendedBio: '',
      hospitalName: 'Mars Hospital',
      experienceYearsCount: '11',
      patientCount: '658',
      reviewsCount: '300',
    ),

  ];
}
