// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU_xwv5MBA1UXhZbSOqnzVi0J_ucW1Gfw',
    appId: '1:274912070764:web:95018570a08d995948dc49',
    messagingSenderId: '274912070764',
    projectId: 'healthso',
    authDomain: 'healthso.firebaseapp.com',
    storageBucket: 'healthso.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyvddxRdAiTRRteSRABuJzSYb_JTrFeZs',
    appId: '1:274912070764:android:66bddd92b2989abb48dc49',
    messagingSenderId: '274912070764',
    projectId: 'healthso',
    storageBucket: 'healthso.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtblsMi8sYzHnLlpqL3zVV7g_Coj965kc',
    appId: '1:274912070764:ios:75f5003eef7ea2b148dc49',
    messagingSenderId: '274912070764',
    projectId: 'healthso',
    storageBucket: 'healthso.appspot.com',
    iosClientId: '274912070764-4aht0jm6b3oul8036pdn0kplnjko786r.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtblsMi8sYzHnLlpqL3zVV7g_Coj965kc',
    appId: '1:274912070764:ios:4b1b55d01cf147e948dc49',
    messagingSenderId: '274912070764',
    projectId: 'healthso',
    storageBucket: 'healthso.appspot.com',
    iosClientId: '274912070764-crr5guuqisme6ju017fed4r78vpbvb8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthso.RunnerTests',
  );
}
